# Generated by Django 4.1 on 2022-09-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_year_alter_borrow_book_alter_borrow_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='book',
        ),
        migrations.AddField(
            model_name='borrow',
            name='book',
            field=models.ManyToManyField(related_name='books', to='books.book'),
        ),
    ]
